namespace Scorm.Scenarios.Demo
{
    /// <summary>One random decision generated by <see cref="ScenarioSimulator"/>.</summary>
    public sealed class SimulatedDecision
    {
        public SimulatedDecision(string id, StudentRecord.InteractionType type, string response, string correctPattern,
            StudentRecord.ResultType result, float latencySeconds, string description)
        {
            Id = id;
            Type = type;
            Response = response;
            CorrectPattern = correctPattern;
            Result = result;
            LatencySeconds = latencySeconds;
            Description = description;
        }

        public string Id { get; }
        public StudentRecord.InteractionType Type { get; }
        public string Response { get; }
        public string CorrectPattern { get; }
        public StudentRecord.ResultType Result { get; }
        public float LatencySeconds { get; }
        public string Description { get; }
    }
}
