using System.Collections.Generic;

namespace Scorm.Scenarios.Demo
{
    /// <summary>Random attempt generated by <see cref="ScenarioSimulator"/>: decisions and the resulting raw score.</summary>
    public sealed class SimulatedAttempt
    {
        public SimulatedAttempt(IReadOnlyList<SimulatedDecision> decisions, float rawScore)
        {
            Decisions = decisions;
            RawScore = rawScore;
        }

        public IReadOnlyList<SimulatedDecision> Decisions { get; }
        public float RawScore { get; }
    }
}
